[package]
name = "phitex-overleaf-core"
version = "0.1.0"
edition = "2024"
license = "AGPL-3.0-only"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
phitex-ssa = { path = "../../../tmp/phitex-0ae189b/crates/phitex-ssa" }
phitex-layout = { path = "../../../tmp/phitex-0ae189b/crates/phitex-layout" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
